### ISSUE TITLE
cargo package できるようにする

### ISSUE THREAD

**Issue by sksat** [arkedge/gaia#108]
#97 でバイナリ配布しようとしていたが，`cargo build` はできるものの `cargo package` が通らず publish できない

**Comment by KOBA789** [comment]
これの解決の見込みどんな感じでしたっけ

**Comment by KOBA789** [comment]
これがブロッカーになってリリースが詰まり始めたので、根本解決を目指さないにせよなんとかしてビルドを通してバイナリ配布を可能にしたい。
ビルドプロセス自体は two-way door なので、一旦多少乱暴でも動くことを優先してしまっていいのではないかと思っています。

**Comment by sksat** [comment]
これがブロッカーになってそうなのはこちらからもかなり見えてるので、最優先でやります

**Comment by KOBA789** [comment]
助かります 🙏 
渋いタスクですまんの……

**Comment by KOBA789** [comment]
publish 順:
- [ ] opslang-wasm
- [ ] devtools-frontend
- [ ] struckpack
- [ ] gaia-stub
- [ ] gaia-ccsds-c2a
- [ ] gaia-tmtc
- [ ] tmtc-c2a

**Comment by KOBA789** [comment]
publish 通った！！！

**Comment by sksat** [comment]
今世紀最大の publish が完了
