### ISSUE TITLE
自動で複数のコマンドを実行する機能が欲しい

### ISSUE THREAD

**Issue by hender14** [arkedge/gaia#45]
## 詳細
毎回コマンド実行を手動で行う必要があるので、複数のコマンドを組み合わせて使用する際に手間がかかっている。
そのため、コマンドを自動で逐次実行していくような機能を追加して欲しい。

また、その際wait系のコマンドも準備して頂けると評価の選択肢が増えるので良いと思う。

## close条件
対応完了したら

## 備考

**Comment by kobkaz** [comment]
opslangがリリースされたので閉じる
