### ISSUE TITLE
HEXタイプのテレメトリをGUI上でも16進数で表示するようにする

### ISSUE THREAD

**Issue by hirotaka912** [arkedge/gaia#46]
TLm database上でConv.TypeがHEXとなっているものは，テレメGUI上でもHEX表示されるようにしたい．現状はConv.TypeがHEXのものも10進数表記になっている．

↓現状の例
アドレスなどは特に10進数で見てもよくわからない

![image](https://github.com/arkedge/c2a-devtools/assets/26454294/6a1c973a-f377-48e6-b30e-2062dae3e876)

**Comment by kobkaz** [comment]
#47 に吸収合併ということでこちらは閉じます
