### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by KOBA789** [arkedge/gaia#48]
目玉は https://github.com/arkedge/gaia/issues/30

**Comment by KOBA789** [comment]
@sksat お願いしていい？

**Comment by sksat** [comment]
OK

**Comment by sksat** [comment]
crates.io には今のところ `structpack` だけある
https://crates.io/crates/structpack

**Comment by sksat** [comment]
- `structpack` 0.6.0 は publish した: https://crates.io/crates/structpack/0.6.0

**Comment by sksat** [comment]
した: https://github.com/arkedge/gaia/releases/tag/v0.6.0
