### ISSUE TITLE
コマンドファイルをまともな言語にする

### ISSUE THREAD

**Issue by KOBA789** [arkedge/gaia#53]
最低でも、ISSL の WINGS 程度の言語を使えるようにしたい（現状は私のやっつけ実装で、機能が足らない）

ref: #45

**Comment by kobkaz** [comment]
確認ですが、あまりWINGとの互換性にこだわる必要はないんですよね？

**Comment by KOBA789** [comment]
fixed by https://github.com/arkedge/gaia/pull/54
